### ISSUE TITLE
installing this toolbox?

### ISSUE THREAD

**Issue by felix-tracxpoint** [Borda/pyImSegm#13]
**How does one install this toolbox, actually?**

1. I wanted to install via pip but 

`pip install pyImgSegm` produces an error

Searching the PyPi website also did not bring up anything.

2. So I cloned the repository and ran the setup.py file, per the readme instructions. But 

`from gco import <something>` still fails.

What am I doing wrong?

**Comment by Borda** [comment]
GCO is not part of this package, the GCO you can find here - https://github.com/Borda/pyGCO
Also, the GCO can be installed as `pip install gco-wrapper`

**Comment by Borda** [comment]
this package is not in PyPi storage, but you can install it locally `python setup.py install`
or throw PyPi `pip install git+https://github.com/Borda/pyImSegm.git`
