### ISSUE TITLE
command wrong

### ISSUE THREAD

**Issue by Sequential-circuits** [Borda/pyImSegm#22]
The command described python experiments_segmentation/run_segm_slic_model_graphcut.py \
   -l ./data_images/langerhans_islets/list_lang-isl_imgs-annot.csv -i "" \
   **--cdf experiments_segmentation/sample_config.yml** \
   -o ./results -n langIsl --nb_classes 3 --visual --nb_workers 2 seems to be wrong
it should be 
python experiments_segmentation/run_segm_slic_model_graphcut.py \
   -l ./data_images/langerhans_islets/list_lang-isl_imgs-annot.csv -i "" \
   -**cfg experiments_segmentation/sample_config.yml** \
   -o ./results -n langIsl --nb_classes 3 --visual --nb_workers 2

**Comment by Borda** [comment]
Thank you, pls note that the experiments are illustration (not necessary updated). It seems that in `experiments_segmentation/test_segmentations.sh` the calling was fine... Fixed in f547f73f64d29dde2e2a350b63d30d2b34b0ce10

**Comment by Sequential-circuits** [comment]
Sure thing, hope that was useful. Great project btw!
