### ISSUE TITLE
No display found. Using non-interactive Agg backend.

### ISSUE THREAD

**Issue by blasco** [Borda/pyImSegm#25]
## Description
I get the following error when importing the package:
"No display found. Using non-interactive Agg backend."

Everything seems to be working but ploting, matplotlib stops working.

**Comment by Borda** [comment]
it seems that you are running on remote mode on a server which does not have a display? or Docker image without mounted display... may you share some more details about your environment?
https://github.com/Borda/pyImSegm/blob/a08c02b3be1cd729b7409dd4c93003e4ab2c0eab/imsegm/utilities/__init__.py#L8-L11

**Comment by blasco** [comment]
You are right, I'm running on a docker image with GPU support for tensorflow

**Comment by Borda** [comment]
Then, restart your session and try get pure Figure without importing this package... I suppose that it fails =)
